#!/usr/bin/env bash

# Args:
#   1. Filename - will be prepended by the date and appended with .tar.gz
#   2. Folder - the folder or file to archive
#   3. Bucket - the b2 bucket to use
_backup_folder() {
    echo "$(date): Creating Backup"
    filename="$(date +'%F')-$1.tar.gz"
    tar czf $filename $2

    enc_filename=encrypted-$filename.gpg
    gpg --output $enc_filename --encrypt -r 15B87AFCCED88630 $filename

    echo "$(date): Saving Backup"
    backedup=$(ls -1 ~/backup_disk | grep $1)
    count=$(($(ls -1 ~/backup_disk | grep $1 | wc -l) - 2))
    for item in $(echo $backedup | head -n $count); do
        rm ~/backup_disk/$item
    done
    mv $filename ~/backup_disk &

    oldfile="$(rclone lsf b2:$3)"
    (rclone move $enc_filename b2:$3 && rclone deletefile --b2-hard-delete b2:$3/$oldfile) &
}

cd ~
##############################
echo "$(date): Backing up notes"
cd ~/notes
git add .
git commit --no-gpg-sign -m "backup"
git push
cd ~

##############################
echo "$(date): Backing up Actual Budget"
_backup_folder actual actual-data chappy-actual-backup

##############################
echo "$(date): Backing up Vaultwarden"
sqlite3 ~/vw-data/db.sqlite3 ".backup '/home/martin/vw-data/db-backup.sqlite3'"

_backup_folder vw vw-data chappy-vw-backup

##############################
cd sentry
echo "$(date): Backing up Sentry"
sqlite3 db/db.sqlite3 ".backup '/home/martin/sentry/db/db-backup.sqlite3'"
sqlite3 db/superset.db ".backup '/home/martin/sentry/db/superset-backup.db'"

_backup_folder sentry db sentry-data-backup

cd ~

##############################
echo "$(date): Backing up photos"

docker exec -t immich_postgres pg_dumpall --clean --if-exists --username=postgres | gzip > "/home/martin/media/photos/dump.sql.gz"
_backup_folder photos "$(echo ~/media/photos/{library,profile,upload,dump.sql.gz})" chappy-server-backup
rm ~/media/photos/dump.sql.gz # Don't need to save random dumps


echo "$(date): Waiting for everything to finish..."
wait

echo "$(date): Done"
