---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab
cardBlur: lg
theme: dark
color: purple
headerStyle: clean
showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: true
disableUpdateCheck: true
layout:
  - Monitoring:
      style: row
      columns: 4
  - Apps:
  - Tinflix:
disableCollapse: true
useEqualHeights: true
statusStyle: dot
