services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --schedule "0 0 2 * * *"
    network_mode: bridge

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr-appdata:/appdata
    env_file: ./.env
    ports:
      - '7575:7575'

  uptime-kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    network_mode: bridge

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_USE_NETWORK_INTERFACE: 'eno1'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    volumes:
      - /:/mnt/host:ro
    ports:
      - '9092:3001'
    network_mode: bridge

volumes:
  kuma-data:
    external: true
    name: kuma-data
