services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --schedule "0 0 2 * * *" --http-api-token "${WATCHTOWER_KEY}" --http-api-metrics
    labels:
      - homepage.group=Monitoring
      - homepage.name=Watchtower
      - homepage.href=#
      - homepage.icon=watchtower
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://watchtower:8080
      - homepage.widget.key=${WATCHTOWER_KEY}

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - ${IP}:3000:3000
    volumes:
      - ./homepage-config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
      - /home/martin/backup_disk:/mnt/backup:ro
    environment:
      #HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      LOG_TARGETS: stdout
      PUID: 1000
      PGID: 1000

  uptime-kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${IP}:3001:3001
    network_mode: bridge
    labels:
      - homepage.group=Monitoring
      - homepage.name=UptimeKuma
      - homepage.href=https://kuma.tinmarr.com
      - homepage.icon=uptime-kuma
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=https://kuma.tinmarr.com
      - homepage.widget.slug=api
      - homepage.widget.fields=["up", "down"]

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_USE_NETWORK_INTERFACE: 'eno1'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    volumes:
      - /:/mnt/host:ro
    ports:
      - ${IP}:9092:3001
    labels:
      - homepage.group=Monitoring
      - homepage.name=Dash.
      - homepage.href=https://dash.tinmarr.com
      - homepage.icon=dashdot

volumes:
  kuma-data:
    external: true
    name: kuma-data
