services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - ${IP}:3000:3000
    volumes:
      - ./homepage-config:/app/config 
      - /home/martin/backup_disk:/mnt/backup:ro
    environment:
      #HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      LOG_TARGETS: stdout
      PUID: 1000
      PGID: 1000

  uptime-kuma:
    container_name: kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${IP}:3001:3001
    user: 1000:1000
    network_mode: bridge
    labels:
      - homepage.group=Monitoring
      - homepage.name=UptimeKuma
      - homepage.href=https://kuma.tinmarr.com
      - homepage.icon=uptime-kuma
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=https://kuma.tinmarr.com
      - homepage.widget.slug=api
      - homepage.widget.fields=["up", "down"]
