# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  system.fsPackages = [
    pkgs.mergerfs
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66272980-77b5-4bec-baa9-a53cee65cb92";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9063-1BC9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/srv/disks/1" = # disk sn ending in 312
    { device = "/dev/disk/by-uuid/a2e7f33b-2d69-4176-9500-ffcb34860632";
      fsType = "ext4";
    };

  fileSystems."/srv/disks/2" = # disk sn ending in 216
    { device = "/dev/disk/by-uuid/caa061e4-35da-45ab-95d2-ec90429f78a4";
      fsType = "ext4";
    };

  fileSystems."/srv/storage" = # mergerfs mount
    { device = "/srv/disks/1:/srv/disks/2";
      fsType = "fuse.mergerfs";

      depends = [
        "/srv/disks/1"
        "/srv/disks/2"
      ];

      options = [
        "defaults"
        "allow_other"
        "category.create=pfrd"
        "minfreespace=20G"
      ];
    };

  swapDevices = [ {
    device = "/.swapfile";
    size = 8000; # in MB
  } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-vaapi-driver   # i965 — correct for Haswell/HD 4600
    ];
  };
  environment.sessionVariables.LIBVA_DRIVER_NAME = "i965";
}
