# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - ${IP}:53:53/tcp
      - ${IP}:53:53/udp
      - ${IP}:8888:80/tcp
    environment:
      TZ: 'America/Montreal'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    labels:
      - homepage.group=Monitoring
      - homepage.name=PiHole
      - homepage.href=https://pihole.tinmarr.com/admin
      - homepage.icon=pi-hole
      - homepage.widget.type=pihole
      - homepage.widget.url=http://192.168.0.10:8888
      - homepage.widget.version=6
      - homepage.widget.key=${PIHOLE_KEY}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

