GENERIC_TIMEZONE=America/Toronto
TZ=America/Toronto
# Default
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
# Isolate n8n
N8N_DIAGNOSTICS_ENABLED=false
N8N_VERSION_NOTIFICATIONS_ENABLED=false
N8N_TEMPLATES_ENABLED=false
# Reverse Proxy
N8N_HOST=n8n.tinmarr.com
N8N_PROTOCOL=https
WEBHOOK_URL=https://n8n.tinmarr.com/
N8N_PROXY_HOPS=2
