services:
  superset:
    build: .
    container_name: superset
    depends_on:
      - psql
    restart: unless-stopped
    environment:
      DB_HOST: psql
    env_file: .env
    ports:
      - ${IP}:9093:8088

  psql:
    image: postgres:alpine
    container_name: psql
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${IP}:5432:5432


